# Generated by Django 3.1.1 on 2021-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='otchestvo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
