# Generated by Django 3.1.1 on 2021-04-14 13:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_otchestvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
